//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerider.Windows.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelerider.Windows.Assets.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the download folder.
        /// </summary>
        internal static string DownloadDialog_FolderBrowerDialogDescription {
            get {
                return ResourceManager.GetString("DownloadDialog_FolderBrowerDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; etc ({1} files) to download list..
        /// </summary>
        internal static string Message_AddedFilesToDownloadList {
            get {
                return ResourceManager.GetString("Message_AddedFilesToDownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; etc ({1} files) to upload list..
        /// </summary>
        internal static string Message_AddedFilesToUploadList {
            get {
                return ResourceManager.GetString("Message_AddedFilesToUploadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; to download list..
        /// </summary>
        internal static string Message_AddedFileToDownloadList {
            get {
                return ResourceManager.GetString("Message_AddedFileToDownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; to upload list..
        /// </summary>
        internal static string Message_AddedFileToUploadList {
            get {
                return ResourceManager.GetString("Message_AddedFileToUploadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added “{0}&quot; folder (includes {1} files) to download list..
        /// </summary>
        internal static string Message_AddedFolderToDownloadList {
            get {
                return ResourceManager.GetString("Message_AddedFolderToDownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Accelerider!.
        /// </summary>
        internal static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
    }
}
