//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerider.Windows.I18nResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelerider.Windows.I18nResources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        internal static string AboutDialog_CheckForUpdate {
            get {
                return ResourceManager.GetString("AboutDialog_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available..
        /// </summary>
        internal static string AboutDialog_CheckUpdateResultAvailable {
            get {
                return ResourceManager.GetString("AboutDialog_CheckUpdateResultAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version. .
        /// </summary>
        internal static string AboutDialog_CheckUpdateResultLatest {
            get {
                return ResourceManager.GetString("AboutDialog_CheckUpdateResultLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Project Home.
        /// </summary>
        internal static string AboutDialog_GithubProjectHome {
            get {
                return ResourceManager.GetString("AboutDialog_GithubProjectHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs4s.
        /// </summary>
        internal static string AboutDialog_Mrs4s {
            get {
                return ResourceManager.GetString("AboutDialog_Mrs4s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Support.
        /// </summary>
        internal static string AboutDialog_Mrs4sDescription {
            get {
                return ResourceManager.GetString("AboutDialog_Mrs4sDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        internal static string AboutDialog_ReleaseNotes {
            get {
                return ResourceManager.GetString("AboutDialog_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerider for Windows.
        /// </summary>
        internal static string AboutDialog_SoftwareName {
            get {
                return ResourceManager.GetString("AboutDialog_SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutDialog_Version {
            get {
                return ResourceManager.GetString("AboutDialog_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.1.
        /// </summary>
        internal static string AboutDialog_VersionNumber {
            get {
                return ResourceManager.GetString("AboutDialog_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZDP.
        /// </summary>
        internal static string AboutDialog_ZDP {
            get {
                return ResourceManager.GetString("AboutDialog_ZDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Desktop Client.
        /// </summary>
        internal static string AboutDialog_ZDPDescription {
            get {
                return ResourceManager.GetString("AboutDialog_ZDPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string AuthenticationWindow_LogIn {
            get {
                return ResourceManager.GetString("AuthenticationWindow_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string AuthenticationWindow_SignUp {
            get {
                return ResourceManager.GetString("AuthenticationWindow_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Buttons_Confirm {
            get {
                return ResourceManager.GetString("Buttons_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Buttons_Submit {
            get {
                return ResourceManager.GetString("Buttons_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Store.
        /// </summary>
        internal static string MainWindow_AppStore {
            get {
                return ResourceManager.GetString("MainWindow_AppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainWindow_Menu {
            get {
                return ResourceManager.GetString("MainWindow_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ProfileDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ProfileDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ProfileDialog_ConfirmPassword {
            get {
                return ResourceManager.GetString("ProfileDialog_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        internal static string ProfileDialog_Email {
            get {
                return ResourceManager.GetString("ProfileDialog_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Visibility: .
        /// </summary>
        internal static string ProfileDialog_EmailVisibility {
            get {
                return ResourceManager.GetString("ProfileDialog_EmailVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Online: .
        /// </summary>
        internal static string ProfileDialog_MultipleOnline {
            get {
                return ResourceManager.GetString("ProfileDialog_MultipleOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ProfileDialog_NewPassword {
            get {
                return ResourceManager.GetString("ProfileDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string ProfileDialog_OldPassword {
            get {
                return ResourceManager.GetString("ProfileDialog_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileDialog_Title {
            get {
                return ResourceManager.GetString("ProfileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        internal static string ProfileDialog_Username {
            get {
                return ResourceManager.GetString("ProfileDialog_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string Punctuation_LeftParenthesis {
            get {
                return ResourceManager.GetString("Punctuation_LeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string Punctuation_RightParenthesis {
            get {
                return ResourceManager.GetString("Punctuation_RightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsPopup_About {
            get {
                return ResourceManager.GetString("SettingsPopup_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerider for Web.
        /// </summary>
        internal static string SettingsPopup_AcceleriderForWeb {
            get {
                return ResourceManager.GetString("SettingsPopup_AcceleriderForWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile.
        /// </summary>
        internal static string SettingsPopup_ChangeProfile {
            get {
                return ResourceManager.GetString("SettingsPopup_ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SettingsPopup_Help {
            get {
                return ResourceManager.GetString("SettingsPopup_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string SettingsPopup_LogOut {
            get {
                return ResourceManager.GetString("SettingsPopup_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPopup_Settings {
            get {
                return ResourceManager.GetString("SettingsPopup_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ShellSettingsTabItem_Application {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-shutdown the computer after the download is complete.
        /// </summary>
        internal static string ShellSettingsTabItem_AutoShutdown {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_AutoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start application.
        /// </summary>
        internal static string ShellSettingsTabItem_AutoStart {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string ShellSettingsTabItem_Header {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On close, keep the application running.
        /// </summary>
        internal static string ShellSettingsTabItem_KeepRunning {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_KeepRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ShellSettingsTabItem_Language {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ShellSettingsTabItem_Theme {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ShellSettingsTabItem_ThemeOptions_Dark {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_ThemeOptions_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ShellSettingsTabItem_ThemeOptions_Light {
            get {
                return ResourceManager.GetString("ShellSettingsTabItem_ThemeOptions_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Login.
        /// </summary>
        internal static string SignInView_AutomaticLogin {
            get {
                return ResourceManager.GetString("SignInView_AutomaticLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignInView_Email {
            get {
                return ResourceManager.GetString("SignInView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string SignInView_Login {
            get {
                return ResourceManager.GetString("SignInView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignInView_Password {
            get {
                return ResourceManager.GetString("SignInView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string SignInView_RememberMe {
            get {
                return ResourceManager.GetString("SignInView_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string SignUpView_EmailAddress {
            get {
                return ResourceManager.GetString("SignUpView_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUpView_Password {
            get {
                return ResourceManager.GetString("SignUpView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string SignUpView_RetrySeconds {
            get {
                return ResourceManager.GetString("SignUpView_RetrySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        internal static string SignUpView_SendCode {
            get {
                return ResourceManager.GetString("SignUpView_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (Nick).
        /// </summary>
        internal static string SignUpView_Username {
            get {
                return ResourceManager.GetString("SignUpView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        internal static string SignUpView_VerificationCode {
            get {
                return ResourceManager.GetString("SignUpView_VerificationCode", resourceCulture);
            }
        }
    }
}
