//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiduPanDownloadWpf.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStringResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaiduPanDownloadWpf.Assets.UiStringResources", typeof(UiStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ABOUT 的本地化字符串。
        /// </summary>
        public static string About_ABOUT {
            get {
                return ResourceManager.GetString("About_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONTACT INFORMATION 的本地化字符串。
        /// </summary>
        public static string About_CONTACT_INFORMATION {
            get {
                return ResourceManager.GetString("About_CONTACT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DONATE 的本地化字符串。
        /// </summary>
        public static string About_DONATE {
            get {
                return ResourceManager.GetString("About_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please let us know if you find any issues about the software. 的本地化字符串。
        /// </summary>
        public static string AboutContactInfoCentent {
            get {
                return ResourceManager.GetString("AboutContactInfoCentent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [b]NOTE:[/b] The software may be disabled at any time by Baidu. 的本地化字符串。
        /// </summary>
        public static string AboutSoftwareAbout {
            get {
                return ResourceManager.GetString("AboutSoftwareAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string ConfigPage_Browse {
            get {
                return ResourceManager.GetString("ConfigPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载路径： 的本地化字符串。
        /// </summary>
        public static string ConfigPage_Download_path_ {
            get {
                return ResourceManager.GetString("ConfigPage_Download_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并行任务： 的本地化字符串。
        /// </summary>
        public static string ConfigPage_Number_of_parallel_tasks_ {
            get {
                return ResourceManager.GetString("ConfigPage_Number_of_parallel_tasks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程数量： 的本地化字符串。
        /// </summary>
        public static string ConfigPage_Speed_limit_ {
            get {
                return ResourceManager.GetString("ConfigPage_Speed_limit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个 的本地化字符串。
        /// </summary>
        public static string ConfigPage_tasks {
            get {
                return ResourceManager.GetString("ConfigPage_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有记录 的本地化字符串。
        /// </summary>
        public static string DownloadedPage_Clear_all_records {
            get {
                return ResourceManager.GetString("DownloadedPage_Clear_all_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载 的本地化字符串。
        /// </summary>
        public static string DownloadedPage_Completed {
            get {
                return ResourceManager.GetString("DownloadedPage_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总完成数： 的本地化字符串。
        /// </summary>
        public static string DownloadedPage_TotalCompleted_ {
            get {
                return ResourceManager.GetString("DownloadedPage_TotalCompleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部取消 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Cancel_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Cancel_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部暂停 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Pause_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Pause_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停中 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Paused {
            get {
                return ResourceManager.GetString("DownloadingPage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部开始 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Start_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Start_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总进度： 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Total_progress_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Total_progress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中... 的本地化字符串。
        /// </summary>
        public static string DownloadingPage_Waiting_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Waiting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string HomePage_delete {
            get {
                return ResourceManager.GetString("HomePage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string HomePage_download {
            get {
                return ResourceManager.GetString("HomePage_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登入 的本地化字符串。
        /// </summary>
        public static string LoginPage_Automatic_login {
            get {
                return ResourceManager.GetString("LoginPage_Automatic_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string LoginPage_Cancel {
            get {
                return ResourceManager.GetString("LoginPage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入 的本地化字符串。
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        public static string LoginPage_Password_ {
            get {
                return ResourceManager.GetString("LoginPage_Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string LoginPage_Remember_the_password {
            get {
                return ResourceManager.GetString("LoginPage_Remember_the_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号：  的本地化字符串。
        /// </summary>
        public static string LoginPage_User_Name_ {
            get {
                return ResourceManager.GetString("LoginPage_User_Name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码： 的本地化字符串。
        /// </summary>
        public static string LoginPage_Verification_code_ {
            get {
                return ResourceManager.GetString("LoginPage_Verification_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎!  的本地化字符串。
        /// </summary>
        public static string LoginPage_Welcome_ {
            get {
                return ResourceManager.GetString("LoginPage_Welcome_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表 的本地化字符串。
        /// </summary>
        public static string MW_download_list {
            get {
                return ResourceManager.GetString("MW_download_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string MW_downloaded {
            get {
                return ResourceManager.GetString("MW_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载 的本地化字符串。
        /// </summary>
        public static string MW_downloading {
            get {
                return ResourceManager.GetString("MW_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件浏览 的本地化字符串。
        /// </summary>
        public static string MW_file_explorer {
            get {
                return ResourceManager.GetString("MW_file_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string MW_help {
            get {
                return ResourceManager.GetString("MW_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件页 的本地化字符串。
        /// </summary>
        public static string MW_home {
            get {
                return ResourceManager.GetString("MW_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        public static string MW_issues {
            get {
                return ResourceManager.GetString("MW_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回收站 的本地化字符串。
        /// </summary>
        public static string MW_recycle_bin {
            get {
                return ResourceManager.GetString("MW_recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string MW_settings {
            get {
                return ResourceManager.GetString("MW_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已分享 的本地化字符串。
        /// </summary>
        public static string MW_shared {
            get {
                return ResourceManager.GetString("MW_shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件 的本地化字符串。
        /// </summary>
        public static string MW_software {
            get {
                return ResourceManager.GetString("MW_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaiduPanDownload（V0.0.10.59 内测版） 的本地化字符串。
        /// </summary>
        public static string MWTitile {
            get {
                return ResourceManager.GetString("MWTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择下载路径 的本地化字符串。
        /// </summary>
        public static string Please_select_the_download_path {
            get {
                return ResourceManager.GetString("Please_select_the_download_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string SettingsPage_about {
            get {
                return ResourceManager.GetString("SettingsPage_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string SettingsPage_configure {
            get {
                return ResourceManager.GetString("SettingsPage_configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入 的本地化字符串。
        /// </summary>
        public static string SettingsPage_login {
            get {
                return ResourceManager.GetString("SettingsPage_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户切换 的本地化字符串。
        /// </summary>
        public static string SettingsPage_user_swich {
            get {
                return ResourceManager.GetString("SettingsPage_user_swich", resourceCulture);
            }
        }
    }
}
