//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiduPanDownloadWpf.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaiduPanDownloadWpf.Assets.UiStringResources", typeof(UiStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string About_ABOUT {
            get {
                return ResourceManager.GetString("About_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFORMATION.
        /// </summary>
        public static string About_CONTACT_INFORMATION {
            get {
                return ResourceManager.GetString("About_CONTACT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        public static string About_DONATE {
            get {
                return ResourceManager.GetString("About_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please let us know if you find any issues about the software..
        /// </summary>
        public static string AboutContactInfoCentent {
            get {
                return ResourceManager.GetString("AboutContactInfoCentent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [b]NOTE:[/b] The software may be disabled at any time by Baidu..
        /// </summary>
        public static string AboutSoftwareAbout {
            get {
                return ResourceManager.GetString("AboutSoftwareAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string ConfigPage_Browse {
            get {
                return ResourceManager.GetString("ConfigPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载路径：.
        /// </summary>
        public static string ConfigPage_Download_path_ {
            get {
                return ResourceManager.GetString("ConfigPage_Download_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 并行任务：.
        /// </summary>
        public static string ConfigPage_Number_of_parallel_tasks_ {
            get {
                return ResourceManager.GetString("ConfigPage_Number_of_parallel_tasks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度限制：.
        /// </summary>
        public static string ConfigPage_Speed_limit_ {
            get {
                return ResourceManager.GetString("ConfigPage_Speed_limit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个.
        /// </summary>
        public static string ConfigPage_tasks {
            get {
                return ResourceManager.GetString("ConfigPage_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除所有记录.
        /// </summary>
        public static string DownloadedPage_Clear_all_records {
            get {
                return ResourceManager.GetString("DownloadedPage_Clear_all_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已下载.
        /// </summary>
        public static string DownloadedPage_Completed {
            get {
                return ResourceManager.GetString("DownloadedPage_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总完成数：.
        /// </summary>
        public static string DownloadedPage_TotalCompleted_ {
            get {
                return ResourceManager.GetString("DownloadedPage_TotalCompleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部取消.
        /// </summary>
        public static string DownloadingPage_Cancel_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Cancel_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部暂停.
        /// </summary>
        public static string DownloadingPage_Pause_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Pause_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停中.
        /// </summary>
        public static string DownloadingPage_Paused {
            get {
                return ResourceManager.GetString("DownloadingPage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部开始.
        /// </summary>
        public static string DownloadingPage_Start_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Start_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总进度：.
        /// </summary>
        public static string DownloadingPage_Total_progress_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Total_progress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待中....
        /// </summary>
        public static string DownloadingPage_Waiting_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Waiting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string HomePage_delete {
            get {
                return ResourceManager.GetString("HomePage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string HomePage_download {
            get {
                return ResourceManager.GetString("HomePage_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动登入.
        /// </summary>
        public static string LoginPage_Automatic_login {
            get {
                return ResourceManager.GetString("LoginPage_Automatic_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string LoginPage_Cancel {
            get {
                return ResourceManager.GetString("LoginPage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码：.
        /// </summary>
        public static string LoginPage_Password_ {
            get {
                return ResourceManager.GetString("LoginPage_Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string LoginPage_Remember_the_password {
            get {
                return ResourceManager.GetString("LoginPage_Remember_the_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号： .
        /// </summary>
        public static string LoginPage_User_Name_ {
            get {
                return ResourceManager.GetString("LoginPage_User_Name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码：.
        /// </summary>
        public static string LoginPage_Verification_code_ {
            get {
                return ResourceManager.GetString("LoginPage_Verification_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎! .
        /// </summary>
        public static string LoginPage_Welcome_ {
            get {
                return ResourceManager.GetString("LoginPage_Welcome_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表.
        /// </summary>
        public static string MW_download_list {
            get {
                return ResourceManager.GetString("MW_download_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string MW_downloaded {
            get {
                return ResourceManager.GetString("MW_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载.
        /// </summary>
        public static string MW_downloading {
            get {
                return ResourceManager.GetString("MW_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件浏览.
        /// </summary>
        public static string MW_file_explorer {
            get {
                return ResourceManager.GetString("MW_file_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string MW_help {
            get {
                return ResourceManager.GetString("MW_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件页.
        /// </summary>
        public static string MW_home {
            get {
                return ResourceManager.GetString("MW_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈.
        /// </summary>
        public static string MW_issues {
            get {
                return ResourceManager.GetString("MW_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回收站.
        /// </summary>
        public static string MW_recycle_bin {
            get {
                return ResourceManager.GetString("MW_recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MW_settings {
            get {
                return ResourceManager.GetString("MW_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已分享.
        /// </summary>
        public static string MW_shared {
            get {
                return ResourceManager.GetString("MW_shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件.
        /// </summary>
        public static string MW_software {
            get {
                return ResourceManager.GetString("MW_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaiduPanDownload (v0.0.8.56).
        /// </summary>
        public static string MWTitile {
            get {
                return ResourceManager.GetString("MWTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择下载路径.
        /// </summary>
        public static string Please_select_the_download_path {
            get {
                return ResourceManager.GetString("Please_select_the_download_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string SettingsPage_about {
            get {
                return ResourceManager.GetString("SettingsPage_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置.
        /// </summary>
        public static string SettingsPage_configure {
            get {
                return ResourceManager.GetString("SettingsPage_configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string SettingsPage_login {
            get {
                return ResourceManager.GetString("SettingsPage_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户切换.
        /// </summary>
        public static string SettingsPage_user_swich {
            get {
                return ResourceManager.GetString("SettingsPage_user_swich", resourceCulture);
            }
        }
    }
}
