//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiduPanDownloadWpf.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaiduPanDownloadWpf.Assets.UiStringResources", typeof(UiStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About_ABOUT {
            get {
                return ResourceManager.GetString("About_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致谢.
        /// </summary>
        public static string About_ACKNOWLEDGEMENTS {
            get {
                return ResourceManager.GetString("About_ACKNOWLEDGEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [size=11][b]Modern UI for WPF (MUI)[/b]: [url=https://github.com/firstfloorsoftware/mui]https://github.com/firstfloorsoftware/mui[/url] (Adapted)
        ///[b]MahApps.Metro[/b]: [url=https://github.com/MahApps/MahApps.Metro]https://github.com/MahApps/MahApps.Metro[/url]
        ///[b]Unity Container[/b]: [url=https://github.com/unitycontainer/unity]https://github.com/unitycontainer/unity[/url]
        ///[b]Prism[/b]: [url=https://github.com/PrismLibrary/Prism]https://github.com/PrismLibrary/Prism[/url]
        ///[b]Icon source[/b]: [url=https: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_ACKNOWLEDGEMENTS_Content {
            get {
                return ResourceManager.GetString("About_ACKNOWLEDGEMENTS_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string About_CONTACT_INFORMATION {
            get {
                return ResourceManager.GetString("About_CONTACT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [b][size=16]捐赠项目[/size][/b]
        ///[size=11]捐赠所得的部分将用于服务器的租用；如果你喜欢本软件，就当请我们喝一杯咖啡。[/size].
        /// </summary>
        public static string About_Donate {
            get {
                return ResourceManager.GetString("About_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [b][size=16]加入我们[/size][/b] 
        ///[size=11]因为众所周知的原因，往往导致开发赶不上和谐。如果你拥有[b]技术[/b]与兴趣，欢迎加入我们，参与开发。
        ///[b]开发者群[/b]：622811874 （或扫左侧二维码，[b]非程[/b][color=#AA808080]序员[/color][b]勿扰[/b]）[/size].
        /// </summary>
        public static string About_JoinUs {
            get {
                return ResourceManager.GetString("About_JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [size=14][b]Mrs4s[/b][/size]
        ///[size=11]- Responsible for Core &amp; Server
        ///[b]Mail:[/b]     [url=mailto:mrs4sxiaoshi@gmail.com]mrs4sxiaoshi@gmail.com[/url]
        ///[b]Blog:[/b]     [url=http://www.mrs4s.top]http://www.mrs4s.top[/url][/size].
        /// </summary>
        public static string About_Mrs4s {
            get {
                return ResourceManager.GetString("About_Mrs4s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持.
        /// </summary>
        public static string About_SUPPORTUS {
            get {
                return ResourceManager.GetString("About_SUPPORTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [size=14][b]ZDP[/b] [color=#FF666666](Laplace&apos;s Demon)[/color][/size]
        ///[size=11]- Responsible for WPF &amp; Infrastructure
        ///[b]Mail:[/b]     [url=mailto:DingpingZhang@outlook.com]DingpingZhang@outlook.com[/url]
        ///[b]Github:[/b] [url=https://github.com/DingpingZhang]github.com/DingpingZhang[/url][/size].
        /// </summary>
        public static string About_ZDP {
            get {
                return ResourceManager.GetString("About_ZDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高调参与开发，低调传播使用。
        ///[b]开源地址[/b]：[url=https://github.com/ResourceHunter/BaiduPanDownloadWpf]https://github.com/ResourceHunter/BaiduPanDownloadWpf[/url]，转载请附上[b]Github链接[/b]及[b]此页面截图[/b]。.
        /// </summary>
        public static string AboutSoftwareAbout {
            get {
                return ResourceManager.GetString("AboutSoftwareAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string ConfigPage_Browse {
            get {
                return ResourceManager.GetString("ConfigPage_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载路径：.
        /// </summary>
        public static string ConfigPage_Download_path_ {
            get {
                return ResourceManager.GetString("ConfigPage_Download_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 并行任务：.
        /// </summary>
        public static string ConfigPage_Number_of_parallel_tasks_ {
            get {
                return ResourceManager.GetString("ConfigPage_Number_of_parallel_tasks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线程数量：.
        /// </summary>
        public static string ConfigPage_Speed_limit_ {
            get {
                return ResourceManager.GetString("ConfigPage_Speed_limit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个.
        /// </summary>
        public static string ConfigPage_tasks {
            get {
                return ResourceManager.GetString("ConfigPage_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除所有记录.
        /// </summary>
        public static string DownloadedPage_Clear_all_records {
            get {
                return ResourceManager.GetString("DownloadedPage_Clear_all_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已下载.
        /// </summary>
        public static string DownloadedPage_Completed {
            get {
                return ResourceManager.GetString("DownloadedPage_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总完成数：.
        /// </summary>
        public static string DownloadedPage_TotalCompleted_ {
            get {
                return ResourceManager.GetString("DownloadedPage_TotalCompleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部取消.
        /// </summary>
        public static string DownloadingPage_Cancel_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Cancel_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部暂停.
        /// </summary>
        public static string DownloadingPage_Pause_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Pause_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停中.
        /// </summary>
        public static string DownloadingPage_Paused {
            get {
                return ResourceManager.GetString("DownloadingPage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部开始.
        /// </summary>
        public static string DownloadingPage_Start_all {
            get {
                return ResourceManager.GetString("DownloadingPage_Start_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总进度：.
        /// </summary>
        public static string DownloadingPage_Total_progress_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Total_progress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待中....
        /// </summary>
        public static string DownloadingPage_Waiting_ {
            get {
                return ResourceManager.GetString("DownloadingPage_Waiting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string HomePage_delete {
            get {
                return ResourceManager.GetString("HomePage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string HomePage_download {
            get {
                return ResourceManager.GetString("HomePage_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动登入.
        /// </summary>
        public static string LoginPage_Automatic_login {
            get {
                return ResourceManager.GetString("LoginPage_Automatic_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string LoginPage_Cancel {
            get {
                return ResourceManager.GetString("LoginPage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码：.
        /// </summary>
        public static string LoginPage_Password_ {
            get {
                return ResourceManager.GetString("LoginPage_Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string LoginPage_Remember_the_password {
            get {
                return ResourceManager.GetString("LoginPage_Remember_the_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号： .
        /// </summary>
        public static string LoginPage_User_Name_ {
            get {
                return ResourceManager.GetString("LoginPage_User_Name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码：.
        /// </summary>
        public static string LoginPage_Verification_code_ {
            get {
                return ResourceManager.GetString("LoginPage_Verification_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎! .
        /// </summary>
        public static string LoginPage_Welcome_ {
            get {
                return ResourceManager.GetString("LoginPage_Welcome_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我遇到了一个难题，想不通，要崩溃了。。。.
        /// </summary>
        public static string MessageDialogContent_Crash {
            get {
                return ResourceManager.GetString("MessageDialogContent_Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string MessageDialogTitle_Error {
            get {
                return ResourceManager.GetString("MessageDialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入异常信息.
        /// </summary>
        public static string MessageDialogTitle_LoginException {
            get {
                return ResourceManager.GetString("MessageDialogTitle_LoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表.
        /// </summary>
        public static string MW_download_list {
            get {
                return ResourceManager.GetString("MW_download_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string MW_downloaded {
            get {
                return ResourceManager.GetString("MW_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载.
        /// </summary>
        public static string MW_downloading {
            get {
                return ResourceManager.GetString("MW_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件浏览.
        /// </summary>
        public static string MW_file_explorer {
            get {
                return ResourceManager.GetString("MW_file_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string MW_help {
            get {
                return ResourceManager.GetString("MW_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件页.
        /// </summary>
        public static string MW_home {
            get {
                return ResourceManager.GetString("MW_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈.
        /// </summary>
        public static string MW_issues {
            get {
                return ResourceManager.GetString("MW_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回收站.
        /// </summary>
        public static string MW_recycle_bin {
            get {
                return ResourceManager.GetString("MW_recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MW_settings {
            get {
                return ResourceManager.GetString("MW_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已分享.
        /// </summary>
        public static string MW_shared {
            get {
                return ResourceManager.GetString("MW_shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件.
        /// </summary>
        public static string MW_software {
            get {
                return ResourceManager.GetString("MW_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcceleRider.
        /// </summary>
        public static string MWTitile {
            get {
                return ResourceManager.GetString("MWTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言：.
        /// </summary>
        public static string OptionPage_Language_ {
            get {
                return ResourceManager.GetString("OptionPage_Language_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string OptionPage_Login_ {
            get {
                return ResourceManager.GetString("OptionPage_Login_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配色：.
        /// </summary>
        public static string OptionPage_Palette_ {
            get {
                return ResourceManager.GetString("OptionPage_Palette_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题：.
        /// </summary>
        public static string OptionPage_Theme_ {
            get {
                return ResourceManager.GetString("OptionPage_Theme_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择下载路径.
        /// </summary>
        public static string Please_select_the_download_path {
            get {
                return ResourceManager.GetString("Please_select_the_download_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string SettingsPage_about {
            get {
                return ResourceManager.GetString("SettingsPage_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置.
        /// </summary>
        public static string SettingsPage_configure {
            get {
                return ResourceManager.GetString("SettingsPage_configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string SettingsPage_login {
            get {
                return ResourceManager.GetString("SettingsPage_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户切换.
        /// </summary>
        public static string SettingsPage_user_swich {
            get {
                return ResourceManager.GetString("SettingsPage_user_swich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string SW_Account {
            get {
                return ResourceManager.GetString("SW_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定百度.
        /// </summary>
        public static string SW_BaiduSignIn {
            get {
                return ResourceManager.GetString("SW_BaiduSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入坐骑.
        /// </summary>
        public static string SW_MountSignIn {
            get {
                return ResourceManager.GetString("SW_MountSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册坐骑.
        /// </summary>
        public static string SW_MountSignUp {
            get {
                return ResourceManager.GetString("SW_MountSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.2.0.79.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
